# Verion of docker-compose to use
version: "3"

services:
  web:
    build:
      context: . #Sets the directory for docker-compose to build.

    # Maps port on the local machine to port on Docker image
    ports:
      - "8000:8000"

    volumes:
      # Copy changes made to the project to your image in real-time.
      - .:/src
    # Handles the command used to run the project in the Docker container.
    command: sh -c "python src/manage.py runserver 0.0.0.0:8000"
